name: Docker Workflow

on:
  push:
    branches:
      - master

jobs:
  build-and-run:
    name: Docker run workflow
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4  # ⬅️ This was missing

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

############################### Angular ###############################
      - name: Build Application docker
        working-directory: ./java/spring_boot_web_apps_gradle/java_applications
        run: |
          docker build -t my-angular-app .
          # docker run -p 8080:80 my-angular-app
          docker tag my-angular-app sreedockerhub19/my-angular-app:latest
          docker push sreedockerhub19/my-angular-app:latest
