name: Docker Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    name: Docker run workflow
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4  # ⬅️ This was missing

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

############################### Angular ###############################
      - name: Build Application docker
        run: |
          docker build -t my-angular-app-main .
          # docker run -p 8080:80 my-angular-app-main
          docker tag my-angular-app-main sreedockerhub19/my-angular-app-main:latest
          docker push sreedockerhub19/my-angular-app-main:latest
